include: "../../smk_load_configs.smk"
include: "../../smk_load_utils.smk"

SAMPLE_SHEET = SAMPLE_SHEETS["vrk_assm"]

SAMPLES = sorted(SAMPLE_SHEET.index.values)
SAMPLES_HG = sorted(
    f"{row.Index}-{row.hg_short}" for row in SAMPLE_SHEET.itertuples()
)

THIS_MODULE = "extract-sex-chromosomes"

MODULE_SUBFOLDER = SUBFOLDERS[THIS_MODULE]
WD = pathlib.Path(MODULE_SUBFOLDER)


rule extract_sex_chromosome_sequence:
    input:
        fasta = lambda wildcards: get_sample_file(SAMPLE_SHEET, wildcards.sample_hg, f"asm_{wildcards.hap}"),
        t2t_ctg = lambda wildcards: get_sample_file(SAMPLE_SHEET, wildcards.sample_hg, f"t2t_ctg"),
        t2t_scf = lambda wildcards: get_sample_file(SAMPLE_SHEET, wildcards.sample_hg, f"t2t_scf"),
    output:
        fasta = WD.joinpath("sequences/{sample_hg}/{sample_hg}.{hap}.{chrom}.fasta"),
        table = WD.joinpath("stats/{sample_hg}/{sample_hg}.{hap}.{chrom}.info.tsv"),
    resources:
        mem_mb = lambda wildcards, attempt: 2048 * attempt
    run:
        import collections as col
        import io
        import re
        import dnaio
        import pandas as pd
        import hashlib as hl

        # NB: these two are not disjoint
        t2t_contigs = read_set_listing(input.t2t_ctg)
        t2t_scaffolds = read_set_listing(input.t2t_scf)

        def skip_seq(chromosome, seq_header):
            if chromosome == "chrUn":
                # hard coded assumption: 'chr' prefix
                # if it exists, we skip
                return seq_header.startswith("chr")
            else:
                # if header does not start with query chromosome,
                # we skip that sequence
                return not seq_header.startswith(chromosome)

        out_table = []
        out_fasta = io.StringIO()
        with dnaio.open(input.fasta) as haplotype:
            for seq_record in haplotype:
                seq_name = seq_record.name
                if skip_seq(wildcards.chrom, seq_name):
                    continue
                if wildcards.chrom == "chrUn":
                    contig_name = seq_name
                else:
                    contig_name = seq_name.split("_", 1)[1]
                seq_number = contig_name.split("-")[-1]
                assert re.match("^[0-9]+$", seq_number)
                seq_number = f"SQN:{seq_number}"

                seq = seq_record.sequence.upper()
                seq_composition = col.Counter(seq)
                seq_length = len(seq)

                if contig_name in t2t_contigs:
                    seq_contiguity = "CTG"
                elif contig_name in t2t_scaffolds:
                    seq_contiguity = "SCF"
                else:
                    seq_contiguity = "FRG"

                if "pat" in seq_name:
                    parent = "PAT"
                elif "mat" in seq_name:
                    parent = "MAT"
                else:
                    parent = "UNK"
                    is_generic_hap1 = "haplotype1" in seq_name
                    is_generic_hap2 = "haplotype2" in seq_name
                    if wildcards.hap != "wg":
                        assert is_generic_hap1 or is_generic_hap2, seq_name

                sample, haplogroup = wildcards.sample_hg.split("-")
                new_name = "|".join(
                    [
                        wildcards.chrom,
                        sample,
                        haplogroup,
                        parent,
                        wildcards.hap,
                        seq_number,
                        seq_contiguity
                    ]
                )
                name_hash_id = hl.md5(new_name.encode("utf-8")).hexdigest()
                name_hash_id = name_hash_id.upper()[:8]
                out_table.append(
                    (
                        sample,
                        wildcards.chrom,
                        seq_name,
                        new_name,
                        name_hash_id,
                        seq_length,
                        seq_composition["A"],
                        seq_composition["C"],
                        seq_composition["G"],
                        seq_composition["T"],
                        seq_composition["N"],
                    )
                )
                out_fasta.write(f">{new_name}\n{seq}\n")

        with open(output.fasta, "w") as dump:
            _ = dump.write(out_fasta.getvalue())

        if out_table:

            table = pd.DataFrame.from_records(
                out_table, columns=[
                    "sample", "chromosome", "source_name", "name", "name_id",
                    "seq_length", "num_A", "num_C", "num_G", "num_T", "num_N"
                ]
            )
            table.sort_values("seq_length", inplace=True, ascending=False)
            table.to_csv(output.table, sep="\t", header=True, index=False)
        else:
            with open(output.table, "w"):
                pass
    # END OF RUN BLOCK


rule ref_align_extracted_sequences:
    input:
        fasta = rules.extract_sex_chromosome_sequence.output.fasta,
        ref = lambda wildcards: WD.joinpath("references", "chm13v2.0.fa.gz")
    output:
        paf = WD.joinpath(
            "ref_orient", "mm2_align",
            "{sample_hg}",
            "{sample_hg}.{hap}.{chrom}.ref-align.paf.gz"
        ),
        tsv = WD.joinpath(
            "ref_orient", "mm2_align",
            "{sample_hg}",
            "{sample_hg}.{hap}.{chrom}.ref-align.norm-paf.tsv.gz"
        )
    conda:
        GLOBAL_CONDA_ENVS.joinpath("align_tools.yaml")
    threads: 6
    resources:
        mem_mb=lambda wildcards, attempt: 24576 * attempt,
        time_hrs=lambda wildcards, attempt: attempt * attempt
    params:
        script=GLOBAL_SCRIPTS.joinpath("normalizer", "normalize_paf.py")
    shell:
        "minimap2 -x asm20 --secondary=no -L --paf-no-hit --eqx "
        "-t {threads} {input.ref} {input.fasta} | gzip > {output.paf}"
            " && "
        "{params.script} --input {output.paf} --output {output.tsv}"


localrules: identify_best_hit_extracted_sequence
rule identify_best_hit_extracted_sequence:
    input:
        tsv = rules.ref_align_extracted_sequences.output.tsv
    output:
        tsv = WD.joinpath(
            "ref_orient", "mm2_align",
            "{sample_hg}",
            "{sample_hg}.{hap}.{chrom}.ref-align.best-hit.tsv"
        )
    run:
        import pandas as pd
        import pandas.errors as pderr

        out_header = [
            "name", "top_hit", "orientation", "seq_length",
            "top_matching_bp", "top_matching_pct"
        ]
        try:
            aln = pd.read_csv(input.tsv, sep="\t", header=0)
        except pderr.EmptyDataError:
            with open(output.tsv, "w") as table:
                table.write("\t".join(out_header) + "\n")
        else:
            best_hit = aln.groupby(
                ["query_name", "query_length", "target_name", "align_orient"]
            )["align_matching"].sum().reset_index(drop=False)
            selected = []
            for query, aln_stats in best_hit.groupby("query_name"):
                top_idx = aln_stats["align_matching"].idxmax()
                top_chrom = aln_stats.loc[top_idx, "target_name"]
                if top_chrom not in ["chrX", "chrY"]:
                    continue
                top_orient = aln_stats.loc[top_idx, "align_orient"]
                top_matching = aln_stats.loc[top_idx, "align_matching"]
                seq_length = aln_stats.loc[top_idx, "query_length"]
                pct_matching = round(top_matching/seq_length * 100, 2)
                selected.append(
                    (query, top_chrom, top_orient, seq_length, top_matching, pct_matching)
                )
            selected = pd.DataFrame.from_records(selected, columns=out_header)
            selected.to_csv(output.tsv, sep="\t", header=True, index=False)
    # END OF RUN BLOCK


localrules: merge_annotation_hit_tables
rule merge_annotation_hit_tables:
    input:
        hap_hits = expand(
            rules.identify_best_hit_extracted_sequence.output.tsv,
            hap=["hap1", "hap2"],
            chrom=["chrX", "chrY"],
            allow_missing=True
        ),
        wg_hits = expand(
            rules.identify_best_hit_extracted_sequence.output.tsv,
            hap=["wg"],
            chrom=["chrUn"],
            allow_missing=True
        ),
        hap_ann = expand(
            rules.extract_sex_chromosome_sequence.output.table,
            hap=["hap1", "hap2"],
            chrom=["chrX", "chrY"],
            allow_missing=True
        ),
        wg_ann = expand(
            rules.extract_sex_chromosome_sequence.output.table,
            hap=["wg"],
            chrom=["chrUn"],
            allow_missing=True
        )
    output:
        tsv = WD.joinpath(
            "ref_orient", "annotated_hits",
            "{sample_hg}.extract-aln-hit.tsv"
        )
    run:
        import pandas as pd
        import pandas.errors as pderr

        def load_tables(table_files):

            concat = []
            for table_file in table_files:
                try:
                    df = pd.read_csv(table_file, sep="\t", header=0)
                    if df.empty:
                        continue
                    concat.append(df)
                except pderr.EmptyDataError:
                    continue
            concat = pd.concat(concat, axis=0, ignore_index=False)
            return concat

        hit_tables = load_tables(
            sorted(input.hap_hits) + sorted(input.wg_hits)
        )
        ann_tables = load_tables(
            sorted(input.hap_ann) + sorted(input.wg_ann)
        )

        merged = ann_tables.merge(hit_tables, on=["name", "seq_length"], how="inner")
        # this inner merge should not shrink the dataset
        merged.to_csv(output.tsv, sep="\t", header=True, index=False)
    # END OF RUN BLOCK


rule reassign_sequences_by_chrom:
    input:
        fasta_wg = expand(
            rules.extract_sex_chromosome_sequence.output.fasta,
            hap=["wg"], chrom=["chrUn"], allow_missing=True
        ),
        fasta_hap = expand(
            rules.extract_sex_chromosome_sequence.output.fasta,
            hap=["hap1", "hap2"], chrom=["chrX", "chrY"], allow_missing=True
        ),
        table = rules.merge_annotation_hit_tables.output.tsv
    output:
        chrom_x = WD.joinpath("seq_short_names/{sample_hg}/{sample_hg}.chrX.fasta"),
        chrom_y = WD.joinpath("seq_short_names/{sample_hg}/{sample_hg}.chrY.fasta"),
    run:
        import io
        import os
        import pandas as pd
        import dnaio

        df = pd.read_csv(input.table, sep="\t", header=0)
        fasta_files = sorted(input.fasta_wg) + sorted(input.fasta_hap)
        buffer_x = io.StringIO()
        buffer_y = io.StringIO()
        for fasta_file in fasta_files:
            file_size = os.stat(fasta_file).st_size
            if file_size == 0:
                continue
            with dnaio.open(fasta_file) as fasta:
                for record in fasta:
                    if record.name not in df["name"].values:
                        continue
                    seq_info = df.loc[df["name"] == record.name, :].iloc[0]
                    if seq_info["orientation"] < 0:
                        out_seq = revcomp(record.sequence)
                    else:
                        out_seq = record.sequence
                    if seq_info["chromosome"] == "chrUn":
                        out_chrom = seq_info["top_hit"]
                    else:
                        try:
                            assert seq_info["chromosome"] == seq_info["top_hit"]
                            out_chrom = seq_info["top_hit"]
                        except AssertionError:
                            if wildcards.sample_hg in ["HG00423-XX", "HG03270-XX"]:
                                # hard-coded exceptions - big chunk of (likely) PAR1
                                # has best hit to chrY, but since both samples are
                                # female, we accept that here to make the rule complete
                                # - exception is documented in central repo readme
                                out_chrom = seq_info["chromosome"]
                                print(f"forcing chromosome {out_chrom} for sample ", wildcards.sample_hg)
                            elif wildcards.sample_hg.endswith("-XX"):
                                # various other female samples (~13) with an unassigned
                                # fragment (usually ~200k or so) mapping to PAR on Y.
                                # Prioritizing logic over data-backed evidence here...
                                # - manually setting required since 'chromosome' is chrUn
                                # HG00735-XX.chrY
                                # HG00423-XX.chrY
                                # HG03816-XX.chrY
                                # HG02841-XX.chrY
                                # HG02922-XX.chrY
                                # NA21106-XX.chrY
                                # HG01784-XX.chrY
                                # HG01175-XX.chrY
                                # HG02165-XX.chrY
                                # HG01969-XX.chrY
                                # HG02257-XX.chrY
                                # NA20282-XX.chrY
                                out_chrom = "chrX"
                                print(f"forcing chromosome {out_chrom} for sample ", wildcards.sample_hg)
                            else:
                                raise

                    name_id = seq_info["name_id"]
                    # minor tweak for female samples just in case
                    if wildcards.sample_hg.endswith("-XX"):
                        long_seq_name = seq_info["name"]
                        if "hap1" in long_seq_name:
                            out_sample = wildcards.sample_hg.replace("-XX", "-XX1")
                        elif "hap2" in long_seq_name:
                            out_sample = wildcards.sample_hg.replace("-XX", "-XX2")
                        elif "wg" in long_seq_name:
                            out_sample = wildcards.sample_hg.replace("-XX", "-XX0")
                        else:
                            raise
                        out_name = f"{out_chrom}_{out_sample}_{name_id}"
                    else:
                        out_name = f"{out_chrom}_{wildcards.sample_hg}_{name_id}"
                    assert len(out_name) < 50  # RepeatMasker
                    if out_chrom == "chrX":
                        buffer_x.write(f">{out_name}\n{out_seq}\n")
                    elif out_chrom == "chrY":
                        buffer_y.write(f">{out_name}\n{out_seq}\n")
                    else:
                        raise

        with open(output.chrom_x, "w") as dump:
            _ = dump.write(buffer_x.getvalue())

        with open(output.chrom_y, "w") as dump:
            _ = dump.write(buffer_y.getvalue())
    # END OF RUN BLOCK


rule merge_sex_chromosome_stat_tables:
    input:
        tables = expand(
            rules.merge_annotation_hit_tables.output.tsv,
            sample_hg=SAMPLES_HG,
        )
    output:
        merged = WD.joinpath("summaries", "seq_rename_composition.tsv")
    run:
        import pandas as pd

        concat = []
        for table_file in input.tables:
            concat.append(pd.read_csv(table_file, sep="\t", header=0))
        table = pd.concat(concat, axis=0, ignore_index=False)
        assert table["name_id"].nunique() == table.shape[0]
        table.sort_values(["sample", "chromosome", "seq_length"], inplace=True, ascending=[True, True, False])
        with open(output.merged, "w") as out:
            _ = out.write(f"#{THIS_MODULE}\n")
            _ = out.write(f"#{get_timestamp()}\n")
            table.to_csv(out, sep="\t", header=True, index=False)
    # END OF RUN BLOCK

#####
##### BELOW - not executed at the moment
#####

rule dump_autosomes:
    input:
        fasta = lambda wildcards: get_sample_file(SAMPLE_SHEET, wildcards.sample_hg, f"asm_{wildcards.hap}"),
        table = rules.merge_sex_chromosome_stat_tables.output.merged
    output:
        fasta = temp(
            WD.joinpath("sequences/{sample_hg}/autosomes/{sample_hg}.{hap}.auto.fasta"),
        )
    resources:
        mem_mb=lambda wildcards, attempt: 8192 * attempt
    run:
        import pandas as pd
        import dnaio
        import io

        table = pd.read_csv(input.table, sep="\t", header=0, comment="#")
        sample = wildcards.sample_hg.split("-")[0]
        sample_set = table.loc[table["sample"] == sample, :].copy()
        sex_seq_names = set(sample_set["source_name"].values)

        buffer = io.StringIO()
        skipped = 0
        with dnaio.open(input.fasta) as fasta:
            for record in fasta:
                if record.name in sex_seq_names:
                    skipped += 1
                    continue
                buffer.write(f">{record.name}\n{record.sequence.upper()}\n")
        assert skipped > 0

        with open(output.fasta, "w") as dump:
            _ = dump.write(buffer.getvalue())
    # END OF RUN BLOCK


rule compress_autosomal_genome:
    input:
        fasta = rules.dump_autosomes.output.fasta
    output:
        fagz = WD.joinpath("sequences/{sample_hg}/autosomes/{sample_hg}.{hap}.auto.fasta.gz"),
        fai = WD.joinpath("sequences/{sample_hg}/autosomes/{sample_hg}.{hap}.auto.fasta.gz.fai")
    conda:
        GLOBAL_CONDA_ENVS.joinpath("seqtools.yaml")
    threads: 4
    resources:
        mem_mb=lambda wildcards, attempt: 2048 * attempt
    shell:
        "bgzip --keep --stdout --threads {threads} {input.fasta} > {output.fagz}"
            " && "
        "samtools faidx {output.fagz}"


rule shorten_sex_chromosome_headers:
    """This rule exists only for old-school
    tools such as RepeatMasker that cannot
    handle arbitrary header names in the
    input fasta files.
    Shorten new names to
    CHROM_SAMPLE-HG_SEQID
    """
    input:
        fasta = rules.extract_sex_chromosome_sequence.output.fasta,
        table = rules.merge_sex_chromosome_stat_tables.output.merged
    output:
        fasta = WD.joinpath("seq_short_names/{sample_hg}/{sample_hg}.{hap}.{chrom}.fasta")
    run:
        raise
        import pandas as pd
        import dnaio
        import io
        import os

        table = pd.read_csv(input.table, sep="\t", header=0, comment="#")
        assert table["name_id"].nunique() == table.shape[0]
        sample = wildcards.sample_hg.split("-")[0]
        sample_set = table.loc[table["sample"] == sample, :].copy()
        # if the respective haplotype did not contain any assembled
        # sequence for that chromosome, the input will be empty
        file_size = os.stat(input.fasta).st_size
        if file_size == 0:
            with open(output.fasta, "w"):
                pass
            with open(output.fasta + ".EMPTY", "w"):
                pass
        else:
            buffer = io.StringIO()
            with dnaio.open(input.fasta) as fasta:
                for record in fasta:
                    seqname = record.name
                    name_id = sample_set.loc[sample_set["name"] == seqname, "name_id"].iloc[0]
                    assert isinstance(name_id, str)
                    short_name = f"{wildcards.chrom}_{wildcards.sample_hg}_{name_id}"
                    assert len(short_name) < 50  # repeatmasker
                    buffer.write(f">{short_name}\n{record.sequence}\n")
            with open(output.fasta, "w") as dump:
                _ = dump.write(buffer.getvalue())
    # END OF RUN BLOCK


rule run_extract_sex_chromosomes:
    input:
        fasta_hap = expand(
            rules.extract_sex_chromosome_sequence.output.fasta,
            sample_hg=SAMPLES_HG,
            hap=["hap1", "hap2"],
            chrom=["chrY", "chrX"]
        ),
        fasta_un = expand(
            rules.extract_sex_chromosome_sequence.output.fasta,
            sample_hg=SAMPLES_HG,
            hap=["wg"],
            chrom=["chrUn"]
        ),
        tsv_hap = expand(
            rules.ref_align_extracted_sequences.output.tsv,
            sample_hg=SAMPLES_HG,
            hap=["hap1", "hap2"],
            chrom=["chrY", "chrX"]
        ),
        tsv_un = expand(
            rules.ref_align_extracted_sequences.output.tsv,
            sample_hg=SAMPLES_HG,
            hap=["wg"],
            chrom=["chrUn"]
        ),
        best_hits_hap = expand(
            rules.identify_best_hit_extracted_sequence.output.tsv,
            sample_hg=SAMPLES_HG,
            hap=["hap1", "hap2"],
            chrom=["chrX", "chrY"]
        ),
        best_hits_wg = expand(
            rules.identify_best_hit_extracted_sequence.output.tsv,
            sample_hg=SAMPLES_HG,
            hap=["wg"],
            chrom=["chrUn"]
        ),
        stats = rules.merge_sex_chromosome_stat_tables.output.merged,
        seqs_x = expand(
            rules.reassign_sequences_by_chrom.output.chrom_x,
            sample_hg=SAMPLES_HG,
        ),
        seqs_y = expand(
            rules.reassign_sequences_by_chrom.output.chrom_y,
            sample_hg=SAMPLES_HG,
        )
        # autosomes = expand(
        #     rules.compress_autosomal_genome.output.fagz,
        #     sample_hg=SAMPLES_HG,
        #     hap=["hap1", "hap2"]
        # ),
        # short_names = expand(
        #     rules.shorten_sex_chromosome_headers.output.fasta,
        #     sample_hg=SAMPLES_HG,
        #     chrom=["chrY", "chrX"],
        #     hap=["hap1", "hap2"]
        # )
