include: "../../smk_load_configs.smk"
include: "../../smk_load_utils.smk"

SAMPLE_SHEET = SAMPLE_SHEETS["vrk_assm"]

SAMPLES = sorted(SAMPLE_SHEET.index.values)
SAMPLES_HG = sorted(
    f"{row.Index}-{row.hg_short}" for row in SAMPLE_SHEET.itertuples()
)

THIS_MODULE = "extract-sex-chromosomes"

MODULE_SUBFOLDER = SUBFOLDERS[THIS_MODULE]
WD = pathlib.Path(MODULE_SUBFOLDER)


rule extract_sex_chromosome_sequence:
    input:
        fasta = lambda wildcards: get_sample_file(SAMPLE_SHEET, wildcards.sample_hg, f"asm_{wildcards.hap}"),
        t2t_ctg = lambda wildcards: get_sample_file(SAMPLE_SHEET, wildcards.sample_hg, f"t2t_ctg"),
        t2t_scf = lambda wildcards: get_sample_file(SAMPLE_SHEET, wildcards.sample_hg, f"t2t_scf"),
    output:
        fasta = WD.joinpath("sequences/{sample_hg}/{sample_hg}.{hap}.{chrom}.fasta"),
        table = WD.joinpath("stats/{sample_hg}/{sample_hg}.{hap}.{chrom}.info.tsv"),
    resources:
        mem_mb = lambda wildcards, attempt: 2048 * attempt
    run:
        import collections as col
        import io
        import re
        import dnaio
        import pandas as pd
        import hashlib as hl

        # NB: these two are not disjoint
        t2t_contigs = read_set_listing(input.t2t_ctg)
        t2t_scaffolds = read_set_listing(input.t2t_scf)

        def skip_seq(chromosome, seq_header):
            if chromosome == "chrUn":
                # hard coded assumption: 'chr' prefix
                # if it exists, we skip
                return seq_header.startswith("chr")
            else:
                # if header does not start with query chromosome,
                # we skip that sequence
                return not seq_header.startswith(chromosome)

        out_table = []
        out_fasta = io.StringIO()
        with dnaio.open(input.fasta) as haplotype:
            for seq_record in haplotype:
                seq_name = seq_record.name
                if skip_seq(wildcards.chrom, seq_name):
                    continue
                if wildcards.chrom == "chrUn":
                    contig_name = seq_name
                else:
                    contig_name = seq_name.split("_", 1)[1]
                seq_number = contig_name.split("-")[-1]
                assert re.match("^[0-9]+$", seq_number)
                seq_number = f"SQN:{seq_number}"

                seq = seq_record.sequence.upper()
                seq_composition = col.Counter(seq)
                seq_length = len(seq)

                if contig_name in t2t_contigs:
                    seq_contiguity = "CTG"
                elif contig_name in t2t_scaffolds:
                    seq_contiguity = "SCF"
                else:
                    seq_contiguity = "FRG"

                if "pat" in seq_name:
                    parent = "PAT"
                elif "mat" in seq_name:
                    parent = "MAT"
                else:
                    parent = "UNK"
                    is_generic_hap1 = "haplotype1" in seq_name
                    is_generic_hap2 = "haplotype2" in seq_name
                    assert is_generic_hap1 or is_generic_hap2, seq_name

                sample, haplogroup = wildcards.sample_hg.split("-")
                new_name = "|".join(
                    [
                        wildcards.chrom,
                        sample,
                        haplogroup,
                        parent,
                        wildcards.hap,
                        seq_number,
                        seq_contiguity
                    ]
                )
                name_hash_id = hl.md5(new_name.encode("utf-8")).hexdigest()
                name_hash_id = name_hash_id.upper()[:8]
                out_table.append(
                    (
                        sample,
                        wildcards.chrom,
                        seq_name,
                        new_name,
                        name_hash_id,
                        seq_length,
                        seq_composition["A"],
                        seq_composition["C"],
                        seq_composition["G"],
                        seq_composition["T"],
                        seq_composition["N"],
                    )
                )
                out_fasta.write(f">{new_name}\n{seq}\n")

        with open(output.fasta, "w") as dump:
            _ = dump.write(out_fasta.getvalue())

        if out_table:

            table = pd.DataFrame.from_records(
                out_table, columns=[
                    "sample", "chromosome", "source_name", "name", "name_id",
                    "seq_length", "num_A", "num_C", "num_G", "num_T", "num_N"
                ]
            )
            table.sort_values("seq_length", inplace=True, ascending=False)
            table.to_csv(output.table, sep="\t", header=True, index=False)
        else:
            with open(output.table, "w"):
                pass
    # END OF RUN BLOCK


rule ref_align_extracted_sequences:
    input:
        fasta = rules.extract_sex_chromosome_sequence.output.fasta,
        ref = lambda wildcards: WD.joinpath("references", "chm13v2.0.fa.gz")
    output:
        paf = WD.joinpath(
            "ref_orient", "mm2_align",
            "{sample_hg}",
            "{sample_hg}.{hap}.{chrom}.ref-align.paf.gz"
        ),
        tsv = WD.joinpath(
            "ref_orient", "mm2_align",
            "{sample_hg}",
            "{sample_hg}.{hap}.{chrom}.ref-align.norm-paf.tsv.gz"
        )
    conda:
        GLOBAL_CONDA_ENVS.joinpath("align_tools.yaml")
    threads: 6
    resources:
        mem_mb=lambda wildcards, attempt: 24576 * attempt,
        time_hrs=lambda wildcards, attempt: attempt * attempt
    params:
        script=GLOBAL_SCRIPTS.joinpath("normalizer", "normalize_paf.py")
    shell:
        "minimap2 -x asm20 --secondary=no -L --paf-no-hit --eqx "
        "-t {threads} -o {output.paf}"
            " && "
        "{params.script} --input {output.paf} --output {output.tsv}"


rule merge_sex_chromosome_stat_tables:
    input:
        tables = expand(
            rules.extract_sex_chromosome_sequence.output.table,
            sample_hg=SAMPLES_HG,
            hap=["hap1", "hap2"],
            chrom=["chrY", "chrX"]
        ),
        tables = expand(
            rules.extract_sex_chromosome_sequence.output.table,
            sample_hg=SAMPLES_HG,
            hap=["wg"],
            chrom=["chrUn"]
        ),
    output:
        merged = WD.joinpath("summaries", "seq_rename_composition.tsv")
    run:
        import pandas as pd

        header = None
        rows = []
        for table_file in input.tables:
            with open(table_file, "r") as table:
                header = table.readline().strip().split()
                if len(header) == 0:
                    continue
                for line in table:
                    rows.append(
                        tuple(line.strip().split())
                    )
        table = pd.DataFrame.from_records(rows, columns=header)
        assert table["name_id"].nunique() == table.shape[0]
        table.sort_values(["sample", "chromosome", "seq_length"], inplace=True, ascending=[True, True, False])
        with open(output.merged, "w") as out:
            _ = out.write(f"#{THIS_MODULE}\n")
            _ = out.write(f"#{get_timestamp()}\n")
            table.to_csv(out, sep="\t", header=True, index=False)
    # END OF RUN BLOCK


rule dump_autosomes:
    input:
        fasta = lambda wildcards: get_sample_file(SAMPLE_SHEET, wildcards.sample_hg, f"asm_{wildcards.hap}"),
        table = rules.merge_sex_chromosome_stat_tables.output.merged
    output:
        fasta = temp(
            WD.joinpath("sequences/{sample_hg}/autosomes/{sample_hg}.{hap}.auto.fasta"),
        )
    resources:
        mem_mb=lambda wildcards, attempt: 8192 * attempt
    run:
        import pandas as pd
        import dnaio
        import io

        table = pd.read_csv(input.table, sep="\t", header=0, comment="#")
        sample = wildcards.sample_hg.split("-")[0]
        sample_set = table.loc[table["sample"] == sample, :].copy()
        sex_seq_names = set(sample_set["source_name"].values)

        buffer = io.StringIO()
        skipped = 0
        with dnaio.open(input.fasta) as fasta:
            for record in fasta:
                if record.name in sex_seq_names:
                    skipped += 1
                    continue
                buffer.write(f">{record.name}\n{record.sequence.upper()}\n")
        assert skipped > 0

        with open(output.fasta, "w") as dump:
            _ = dump.write(buffer.getvalue())
    # END OF RUN BLOCK


rule compress_autosomal_genome:
    input:
        fasta = rules.dump_autosomes.output.fasta
    output:
        fagz = WD.joinpath("sequences/{sample_hg}/autosomes/{sample_hg}.{hap}.auto.fasta.gz"),
        fai = WD.joinpath("sequences/{sample_hg}/autosomes/{sample_hg}.{hap}.auto.fasta.gz.fai")
    conda:
        GLOBAL_CONDA_ENVS.joinpath("seqtools.yaml")
    threads: 4
    resources:
        mem_mb=lambda wildcards, attempt: 2048 * attempt
    shell:
        "bgzip --keep --stdout --threads {threads} {input.fasta} > {output.fagz}"
            " && "
        "samtools faidx {output.fagz}"


rule shorten_sex_chromosome_headers:
    """This rule exists only for old-school
    tools such as RepeatMasker that cannot
    handle arbitrary header names in the
    input fasta files.
    Shorten new names to
    CHROM_SAMPLE-HG_SEQID
    """
    input:
        fasta = rules.extract_sex_chromosome_sequence.output.fasta,
        table = rules.merge_sex_chromosome_stat_tables.output.merged
    output:
        fasta = WD.joinpath("seq_short_names/{sample_hg}/{sample_hg}.{hap}.{chrom}.fasta")
    run:
        import pandas as pd
        import dnaio
        import io
        import os

        table = pd.read_csv(input.table, sep="\t", header=0, comment="#")
        assert table["name_id"].nunique() == table.shape[0]
        sample = wildcards.sample_hg.split("-")[0]
        sample_set = table.loc[table["sample"] == sample, :].copy()
        # if the respective haplotype did not contain any assembled
        # sequence for that chromosome, the input will be empty
        file_size = os.stat(input.fasta).st_size
        if file_size == 0:
            with open(output.fasta, "w"):
                pass
            with open(output.fasta + ".EMPTY", "w"):
                pass
        else:
            buffer = io.StringIO()
            with dnaio.open(input.fasta) as fasta:
                for record in fasta:
                    seqname = record.name
                    name_id = sample_set.loc[sample_set["name"] == seqname, "name_id"].iloc[0]
                    assert isinstance(name_id, str)
                    short_name = f"{wildcards.chrom}_{wildcards.sample_hg}_{name_id}"
                    assert len(short_name) < 50  # repeatmasker
                    buffer.write(f">{short_name}\n{record.sequence}\n")
            with open(output.fasta, "w") as dump:
                _ = dump.write(buffer.getvalue())
    # END OF RUN BLOCK


rule run_extract_sex_chromosomes:
    input:
        fasta_hap = expand(
            rules.extract_sex_chromosome_sequence.output.fasta,
            sample_hg=SAMPLES_HG,
            hap=["hap1", "hap2"],
            chrom=["chrY", "chrX"]
        ),
        fasta_un = expand(
            rules.extract_sex_chromosome_sequence.output.fasta,
            sample_hg=SAMPLES_HG,
            hap=["wg"],
            chrom=["chrUn"]
        ),
        tsv_hap = expand(
            rules.ref_align_extracted_sequences.output.tsv,
            sample_hg=SAMPLES_HG,
            hap=["hap1", "hap2"],
            chrom=["chrY", "chrX"]
        ),
        tsv_un = expand(
            rules.ref_align_extracted_sequences.output.tsv,
            sample_hg=SAMPLES_HG,
            hap=["wg"],
            chrom=["chrUn"]
        ),
        # stats = rules.merge_sex_chromosome_stat_tables.output.merged,
        # autosomes = expand(
        #     rules.compress_autosomal_genome.output.fagz,
        #     sample_hg=SAMPLES_HG,
        #     hap=["hap1", "hap2"]
        # ),
        # short_names = expand(
        #     rules.shorten_sex_chromosome_headers.output.fasta,
        #     sample_hg=SAMPLES_HG,
        #     chrom=["chrY", "chrX"],
        #     hap=["hap1", "hap2"]
        # )
