include: "../../smk_load_configs.smk"
include: "../../smk_load_utils.smk"

SAMPLE_SHEET = SAMPLE_SHEETS["vrk_assm"]

SAMPLES = sorted(SAMPLE_SHEET.index.values)
SAMPLES_HG = sorted(
    f"{row.Index}-{row.hg_short}" for row in SAMPLE_SHEET.itertuples()
)

THIS_MODULE = "extract-sex-chromosomes"

MODULE_SUBFOLDER = SUBFOLDERS[THIS_MODULE]
WD = pathlib.Path(MODULE_SUBFOLDER)


rule extract_sex_chromosome_sequence:
    input:
        fasta = lambda wildcards: get_sample_file(SAMPLE_SHEET, wildcards.sample_hg, f"asm_{wildcards.hap}"),
        t2t_ctg = lambda wildcards: get_sample_file(SAMPLE_SHEET, wildcards.sample_hg, f"t2t_ctg"),
        t2t_scf = lambda wildcards: get_sample_file(SAMPLE_SHEET, wildcards.sample_hg, f"t2t_scf"),
    output:
        fasta = WD.joinpath("sequences/{sample_hg}/{sample_hg}.{hap}.{chrom}.fasta"),
        table = WD.joinpath("stats/{sample_hg}/{sample_hg}.{hap}.{chrom}.info.tsv"),
    resources:
        mem_mb = lambda wildcards, attempt: 2048 * attempt
    run:
        import collections as col
        import io
        import re
        import dnaio
        import pandas as pd
        import hashlib as hl

        # NB: these two are not disjoint
        t2t_contigs = read_set_listing(input.t2t_ctg)
        t2t_scaffolds = read_set_listing(input.t2t_scf)

        out_table = []
        out_fasta = io.StringIO()
        with dnaio.open(input.fasta) as haplotype:
            for seq_record in haplotype:
                seq_name = seq_record.name
                if not seq_name.startswith(wildcards.chrom):
                    continue
                contig_name = seq_name.split("_", 1)[1]
                seq_number = contig_name.split("-")[-1]
                assert re.match("^[0-9]+$", seq_number)
                seq_number = f"SQN:{seq_number}"

                seq = seq_record.sequence.upper()
                seq_composition = col.Counter(seq)
                seq_length = len(seq)

                if contig_name in t2t_contigs:
                    seq_contiguity = "CTG"
                elif contig_name in t2t_scaffolds:
                    seq_contiguity = "SCF"
                else:
                    seq_contiguity = "FRG"

                if "pat" in seq_name:
                    parent = "PAT"
                elif "mat" in seq_name:
                    parent = "MAT"
                else:
                    parent = "UNK"
                    is_generic_hap1 = "haplotype1" in seq_name
                    is_generic_hap2 = "haplotype2" in seq_name
                    assert is_generic_hap1 or is_generic_hap2, seq_name

                sample, haplogroup = wildcards.sample_hg.split("-")
                new_name = "|".join(
                    [
                        wildcards.chrom,
                        sample,
                        haplogroup,
                        parent,
                        wildcards.hap,
                        seq_number,
                        seq_contiguity
                    ]
                )
                name_hash_id = hl.md5(new_name.encode("utf-8")).hexdigest()
                name_hash_id = name_hash_id.upper()[:8]
                out_table.append(
                    (
                        sample,
                        wildcards.chrom,
                        seq_name,
                        new_name,
                        name_hash_id,
                        seq_length,
                        seq_composition["A"],
                        seq_composition["C"],
                        seq_composition["G"],
                        seq_composition["T"],
                        seq_composition["N"],
                    )
                )
                out_fasta.write(f">{new_name}\n{seq}\n")

        with open(output.fasta, "w") as dump:
            _ = dump.write(out_fasta.getvalue())

        if out_table:

            table = pd.DataFrame.from_records(
                out_table, columns=[
                    "sample", "chromosome", "source_name", "name", "name_id",
                    "seq_length", "num_A", "num_C", "num_G", "num_T", "num_N"
                ]
            )
            table.sort_values("seq_length", inplace=True, ascending=False)
            table.to_csv(output.table, sep="\t", header=True, index=False)
        else:
            with open(output.table, "w"):
                pass
    # END OF RUN BLOCK


rule merge_sex_chromosome_stat_tables:
    input:
        tables = expand(
            rules.extract_sex_chromosome_sequence.output.table,
            sample_hg=SAMPLES_HG,
            hap=["hap1", "hap2"],
            chrom=["chrY", "chrX"]
        )
    output:
        merged = WD.joinpath("summaries", "seq_rename_composition.tsv")
    run:
        import pandas as pd

        header = None
        rows = []
        for table_file in input.tables:
            with open(table_file, "r") as table:
                header = table.readline().strip().split()
                if len(header) == 0:
                    continue
                for line in table:
                    rows.append(
                        tuple(line.strip().split())
                    )
        table = pd.DataFrame.from_records(rows, columns=header)
        table.sort_values(["sample", "chromosome", "seq_length"], inplace=True, ascending=[True, True, False])
        with open(output.merged, "w") as out:
            _ = out.write(f"#{THIS_MODULE}\n")
            _ = out.write(f"#{get_timestamp()}\n")
            table.to_csv(out, sep="\t", header=True, index=False)
    # END OF RUN BLOCK


rule run_extract_sex_chromosomes:
    input:
        fasta = expand(
            rules.extract_sex_chromosome_sequence.output.fasta,
            sample_hg=SAMPLES_HG,
            hap=["hap1", "hap2"],
            chrom=["chrY", "chrX"]
        ),
        stats = rules.merge_sex_chromosome_stat_tables.output.merged
