import pathlib

include: "../../smk_load_configs.smk"
include: "../../smk_load_utils.smk"

include: "rules/pyutils.smk"

THIS_MODULE = "postproc-region-labels"

MODULE_SUBFOLDER = SUBFOLDERS[THIS_MODULE]
WD = pathlib.Path(MODULE_SUBFOLDER)

SAMPLE_SHEET = SAMPLE_SHEETS["vrk_chrY_arhie_freeze"]
SAMPLES=SAMPLE_SHEET.index.values

WF_SEQANN_WD = pathlib.Path(
    PROJECT_CONFIG["remote_hilbert_prefix"],
    PROJECT_CONFIG["hilbert_wf_seqann_folder"]
).resolve(strict=True)


MODULE_REF_GENOMES = {
    "t2tv2": "HG002-Y_T2Tv2_CP086569.2.fasta",
    "hg38": "GRCh38.p14_chrY_CM000686.2.fasta"
}

MODULE_REF_LABELINGS = {
    "t2tv2": "HG002-Y_T2Tv2_regions_repeat-details.bed",
    "hg38": "GRCh38-Y_regions_repeat-details.bed"
}


include: "rules/10_realign_regions.smk"
include: "rules/20_color_blocks_compare.smk"
include: "rules/30_color_blocks_uniqk.smk"



rule merge_aln_and_kmer_annotation:
    input:
        aln_bed = rules.check_realign_precision.output.bed,
        strand_kmer_tsv = rules.normalize_kmer_based_color_annotation.output.tsv_dir,
        uniq_color_kmer_tsv = rules.normalize_color_unique_kmer_counts.output.tsv_dir
    output:
        bed = WD.joinpath(
            "region_labels_aln_kmers",
            "{sample}.{ref}.chrY-regions.aln-kmer-merged.bed"
        )
    conda:
        GLOBAL_CONDA_ENVS.joinpath("seqtools.yaml")
    params:
        script=PROJECT_REPO_ROOT.joinpath(
            "codebase", "postproc-region-labels", "workflow",
            "scripts", "merge_kmer_annotation.py"
        ).resolve(strict=True),
        kmer_strand_info = lambda wildcards, input: pathlib.Path(
            input.strand_kmer_tsv,
            f"{wildcards.sample}.chrY-regions-kmer-annot.bed"
        ),
        kmer_color_info = lambda wildcards, input: pathlib.Path(
            input.uniq_color_kmer_tsv,
            f"{wildcards.sample}_chrY-regions_uniq-kmer-counts.tsv"
        ),
    shell:
        "{params.script} --aln-region-labels {input.aln_bed} "
        "--kmer-strands {params.kmer_strand_info} "
        "--kmer-region-labels {params.kmer_color_info} "
        "--output {output.bed}"


localrules: normalize_filtered_hmmer_hits
rule normalize_filtered_hmmer_hits:
    """This rule is highly application-specific because
    it depends on externally filtered high-quality HMMER
    hit (provided by Mark Loftus). These data come in slightly
    non-uniform format and must be normalized first.
    """
    input:
        hmmer_filtered = [
            pathlib.Path(PROJECT_CONFIG["remote_hilbert_prefix"]).joinpath(PROJECT_CONFIG["hmmer_filtered_dyz19"]),
            pathlib.Path(PROJECT_CONFIG["remote_hilbert_prefix"]).joinpath(PROJECT_CONFIG["hmmer_filtered_tspy"]),
            pathlib.Path(PROJECT_CONFIG["remote_hilbert_prefix"]).joinpath(PROJECT_CONFIG["hmmer_filtered_yq12"])
        ]
    output:
        hmmer_motifs = expand(
            WD.joinpath(
                "hmmer_filtered_hits", "{motif}",
                "{sample}.{motif}.chrY-hmmer-filtered-hits.bed"
            ),
            sample=SAMPLES,
            motif=["tspy", "dyz19", "yq12"]
        )
    run:

        for folder in input.hmmer_filtered:
            folder = pathlib.Path(folder).resolve(strict=True)
            motif_name = folder.name.replace("hmmerFilter", "")
            assert motif_name in ["tspy", "dyz19", "yq12"]
            for csv_file in folder.glob("**/*.csv"):
                if "old" in str(csv_file.parent):
                    continue
                sample = csv_file.name.split(".")[0]
                bed_df = load_ml_motif_hits(csv_file, motif_name)
                out_file = WD.joinpath(
                    "hmmer_filtered_hits", f"{motif_name}",
                    f"{sample}.{motif_name}.chrY-hmmer-filtered-hits.bed"
                )
                bed_df.to_csv(out_file, sep="\t", header=True, index=False)
    # END OF RUN BLOCK


localrules: merge_hmmer_hits_into_aln_kmer_regions
rule merge_hmmer_hits_into_aln_kmer_regions:
    input:
        regions = rules.merge_aln_and_kmer_annotation.output.bed,
        hmmer_hits = expand(
            WD.joinpath(
                "hmmer_filtered_hits", "{motif}",
                "{sample}.{motif}.chrY-hmmer-filtered-hits.bed"
            ),
            motif=["tspy", "dyz19", "yq12"],
            allow_missing=True
        )
    output:
        bed = WD.joinpath(
            "aln_kmer_hmmer", "merged_wo_qc",
            "{sample}.{ref}.chrY-regions.aln-kmer-hmmer.bed"
        )
    run:
        import pandas as pd
        import re

        hmmer = []
        for bed_file in input.hmmer_hits:
            motif = pd.read_csv(bed_file, sep="\t", header=0)
            hmmer.append(motif)
        hmmer = pd.concat(hmmer, axis=0, ignore_index=False)

        regions = pd.read_csv(input.regions, sep="\t", header=0)

        tag_motifs = build_redundant_motif_filter(set(
            ["tspy", "dyz19", "yq12"] + hmmer["name"].tolist()
        ))

        regions["is_replaced"] = regions["name"].apply(tag_motifs) | regions["second_best_guess"].apply(tag_motifs)
        regions = regions.loc[~regions["is_replaced"], :].copy()

        regions.drop("is_replaced", axis=1, inplace=True)

        hmmer["thickStart"] = hmmer["start"]
        hmmer["thickEnd"] = hmmer["end"]
        hmmer["assign_method"] = "hmmer"
        hmmer["second_best_guess"] = hmmer["name"]
        hmmer["kmer_top_enrich"] = 0
        hmmer["other_support"] = "unknown"
        hmmer["other_orientation"] = "."
        hmmer["cluster_id"] = -1

        regions = pd.concat([regions, hmmer], axis=0, ignore_index=False)
        regions.sort_values(["#seq", "start", "end"], inplace=True)

        assert not pd.isnull(regions).any(axis=0).any()

        regions.to_csv(output.bed, sep="\t", header=True, index=False)
    # END OF RUN BLOCK


localrules: draft_summary_region_annotation
rule draft_summary_region_annotation:
    input:
        table = rules.merge_hmmer_hits_into_aln_kmer_regions.output.bed
    output:
        tsv = WD.joinpath(
            "statistics", "merged_wo_qc",
            "{sample}.{ref}.chrY-regions.aln-kmer-hmmer.stats.tsv"
        )
    run:
        import pandas as pd

        df = pd.read_csv(input.table, sep="\t", header=0)
        df["length"] = df["end"] - df["start"]

        grand_total = df["length"].sum()
        label_total = df.groupby("name")["length"].sum()
        label_total["total"] = grand_total
        label_total["sample"] = wildcards.sample
        label_total["ref"] = wildcards.ref

        label_total.to_csv(output.tsv, sep="\t", header=True, index=True)
    # END OF RUN BLOCK


rule run_all_postproc_labels:
    """potential TODO: add the reference kmer annotation
    analogous to the sample-level kmer annotation to
    have a proper baseline for accuracy
    (needs to be done by ML)
    """
    input:
        tsv = expand(
            rules.draft_summary_region_annotation.output.tsv,
            sample=[sample for sample in SAMPLES if sample not in ["RFGRC38-R1", "RFCHM13-J1"]],
            ref=list(MODULE_REF_GENOMES.keys())
        ),
        kmer_tsv = rules.normalize_kmer_based_color_annotation.output.tsv_dir,
        uniq_kmer_tsv = rules.normalize_color_unique_kmer_counts.output.tsv_dir,
        hmmer_motif_hits = rules.normalize_filtered_hmmer_hits.output.hmmer_motifs
