import pathlib

include: "../../smk_load_configs.smk"
include: "../../smk_load_utils.smk"

include: "rules/pyutils.smk"

THIS_MODULE = "postproc-region-labels"

MODULE_SUBFOLDER = SUBFOLDERS[THIS_MODULE]
WD = pathlib.Path(MODULE_SUBFOLDER)

SAMPLE_SHEET = SAMPLE_SHEETS["vrk_chrY_arhie"]
SAMPLES=SAMPLE_SHEET.index.values

WF_SEQANN_WD = pathlib.Path(
    PROJECT_CONFIG["remote_hilbert_prefix"],
    PROJECT_CONFIG["hilbert_wf_seqann_folder"]
).resolve(strict=True)


MODULE_REF_GENOMES = {
    "t2tv2": "HG002-Y_T2Tv2_CP086569.2.fasta",
    "hg38": "GRCh38.p14_chrY_CM000686.2.fasta"
}

MODULE_REF_LABELINGS = {
    "t2tv2": "HG002-Y_T2Tv2_regions_repeat-details.bed",
    "hg38": "GRCh38-Y_regions_repeat-details.bed"
}


rule merge_region_by_coord_and_name:
    """The script first simplifies the region labels
    and then merges them by overlap (default: 1 bp) and name
    """
    input:
        sample_region_labels=lambda wildcards: WF_SEQANN_WD.joinpath(
            "results", "annotations", "combined"
        ).glob(f"{wildcards.sample}.*cmb-{wildcards.ref}.concat.bed.gz")
    output:
        bed_file = WD.joinpath(
            "region_labels", "merged",
            "{sample}.{ref}.chrY-regions-merged.bed.gz"
        )
    conda:
        GLOBAL_CONDA_ENVS.joinpath("seqtools.yaml")
    params:
        script=PROJECT_REPO_ROOT.joinpath(
            "codebase", "postproc-region-labels", "workflow",
            "scripts", "merge_by_ovl_and_name.py"
        ).resolve(strict=True)
    shell:
        "{params.script} --bed-in {input.sample_region_labels} "
        "--merge-dist 1 --bed-out {output.bed_file}"


rule extract_labeled_sequences:
    input:
        bed_file = rules.merge_region_by_coord_and_name.output.bed_file,
        fasta = lambda wildcards: get_sample_file(SAMPLE_SHEET, wildcards.sample, "input_path")
    output:
        fasta = WD.joinpath(
            "region_seqs", "{sample}.{ref}.chrY-regions.fasta"
        ),
    conda:
        GLOBAL_CONDA_ENVS.joinpath("seqtools.yaml")
    shell:
        "bedtools getfasta -fi {input.fasta} -bed {input.bed_file} -name -fo {output.fasta}"


rule ref_align_extracted_sequences:
    input:
        fasta = rules.extract_labeled_sequences.output.fasta,
        ref = lambda wildcards: WD.joinpath("references", f"{MODULE_REF_GENOMES[wildcards.ref]}")
    output:
        paf = WD.joinpath(
            "region_alignments",
            "{sample}.{ref}.chrY-regions-realigned.paf.gz"
        )
    conda:
        GLOBAL_CONDA_ENVS.joinpath("align_tools.yaml")
    threads: 4
    resources:
        mem_mb=lambda wildcards, attempt: 4096 * attempt * attempt,
    shell:
        "minimap2 -x asm20 --eqx -c -t {threads} -N 0 --secondary=no "
        "{input.ref} {input.fasta} | gzip > {output.paf}"


rule normalize_realigned_region_seqs:
    input:
        paf = rules.ref_align_extracted_sequences.output.paf
    output:
        tsv = WD.joinpath(
            "region_alignments",
            "{sample}.{ref}.chrY-regions-realigned.norm-paf.tsv.gz"
        )
    conda:
        GLOBAL_CONDA_ENVS.joinpath("align_tools.yaml")
    params:
        script=GLOBAL_SCRIPTS.joinpath("normalizer", "normalize_paf.py")
    shell:
        "{params.script} --input {input.paf} --output {output.tsv}"


rule check_realign_precision:
    input:
        tsv = rules.normalize_realigned_region_seqs.output.tsv,
        labels = lambda wildcards: lambda wildcards: WD.joinpath("references", f"{MODULE_REF_LABELINGS[wildcards.ref]}")
    output:
        tmp = temp(WD.joinpath(
            "region_alignments",
            "{sample}.{ref}.chrY-regions-realigned.tmp.bed"
        )),
        bed = WD.joinpath(
            "region_alignments",
            "{sample}.{ref}.chrY-regions-realigned.bed.gz"
        ),
    conda:
        GLOBAL_CONDA_ENVS.joinpath("seqtools.yaml")
    params:
        script=PROJECT_REPO_ROOT.joinpath(
            "codebase", "postproc-region-labels", "workflow",
            "scripts", "check_realign_precision.py"
        ).resolve(strict=True)
    shell:
        "{params.script} --input-aln {input.tsv} --input-regions {input.labels} "
        "--output-regions {output.tmp}"
            " && "
        "bgzip -c {output.tmp} > {output.bed}"
            " && "
        "tabix -p bed {output.bed}"


localrules: unzip_kmer_based_color_annotation
rule unzip_kmer_based_color_annotation:
    input:
        zip = PROJECT_REPO_ROOT.joinpath(
            "annotation", "raw", "20250710_ColorBlockComparisonArang_v2.ML.zip",
        ).resolve(strict=True)
    output:
        csv_dir = directory(WD.joinpath("region_kmer_annot", "raw_csv"))
    shell:
        "unzip -j -d {output.csv_dir} {input.zip}"


localrules: merge_xyy_sample_blocks
rule merge_xyy_sample_blocks:
    """Because he is such a cool dude by his own standards,
    ML put the two chrY copies of the XYY sample HG03456
    into separate files.
    Re-merge them here to have the workflow work as before
    (w/o the HGSVC sample set).
    """
    input:
        csv_dir = rules.unzip_kmer_based_color_annotation.output.csv_dir
    output:
        check = WD.joinpath("region_kmer_annot", "hg03456_xyy_blocks_merged.ok")
    params:
        seq1 = pathlib.Path(
            rules.unzip_kmer_based_color_annotation.output.csv_dir
        ).joinpath(
            "ColorBlockComparisonArang",
            "HG03456_chrY_1_E1b1a1a1a1c1b_ColorBlockRegions.wArang.csv"
        ),
        seq2 = pathlib.Path(
            rules.unzip_kmer_based_color_annotation.output.csv_dir
        ).joinpath(
            "ColorBlockComparisonArang",
            "HG03456_chrY_2_E1b1a1a1a1c1b_ColorBlockRegions.wArang.csv"
        ),
        out = pathlib.Path(
            rules.unzip_kmer_based_color_annotation.output.csv_dir
        ).joinpath(
            "ColorBlockComparisonArang",
            "HG03456_chrY_E1b1a1a1a1c1b_ColorBlockRegions.wArang.csv"
        )
    run:
        out_lines = []
        total_lines = 0
        assert str(params.seq1) != str(params.seq2)
        for csv_file in [params.seq1, params.seq2]:
            read_header = "_chrY_1_" in str(csv_file)
            with open(csv_file, "r") as listing:
                if read_header:
                    out_lines.append(listing.readline().strip())
                else:
                    # skip header of second file
                    _ = listing.readline()
                for line in listing:
                    ln = total_lines
                    data_part = line.strip().split(",", 1)[-1]
                    out_lines.append(
                        f"{ln},{data_part}"
                    )
                    total_lines += 1
        with open(params.out, "w") as dump:
            _ = dump.write("\n".join(out_lines))
    # END OF RUN BLOCK


localrules: normalize_kmer_based_color_annotation
rule normalize_kmer_based_color_annotation:
    input:
        xyy_mrg = rules.merge_xyy_sample_blocks.output.check,
        csv_dir = rules.unzip_kmer_based_color_annotation.output.csv_dir
    output:
        tsv_dir = directory(WD.joinpath("region_kmer_annot", "norm_tsv"))
    run:
        import pandas as pd
        import pathlib as pl
        import sys

        # from pyutils module
        # bring to local scope
        norm_label = normalize_label_name

        for csv_file in pl.Path(input.csv_dir).glob("*.csv"):
            # the format is of course idiosyncratic
            file_name = csv_file.name
            if not any(file_name.startswith(sample) for sample in SAMPLES):
                sys.stderr.write(f"\nWarning: skipping file - likely not a sample file: {file_name}\n")
                continue  # skip files that do not match any sample name
            if "_chrY_1_" in file_name or "_chrY_2_" in file_name:
                sys.stderr.write(f"\nSkipping unmerged HG03456-XYY: {file_name}\n")
                continue  # see previous rule
            new_tsv = []
            sample_name = csv_file.stem.split("_")[0]
            with open(csv_file, "r", encoding="ascii") as table_like:
                _ = table_like.readline()  # skip header
                for line in table_like:
                    columns = line.strip().split(",")
                    seq_name = columns[1]
                    region_start = int(columns[3])
                    region_end = int(columns[4])
                    # fix LOFTUS-coding...
                    region_label = norm_label(columns[5])
                    orientation = columns[6]
                    if orientation == "sense":
                        orientation = "+"
                    elif orientation == "antisense":
                        orientation = "-"
                    else:
                        raise ValueError(f"Unknown orientation: {orientation}")
                    row = (seq_name, region_start, region_end, region_label, 1000, orientation)
                    new_tsv.append(row)
            new_tsv = pd.DataFrame(
                new_tsv,
                columns=["#seq_name", "start", "end", "name", "score", "strand"]
            )
            new_tsv.sort_values(["#seq_name", "start"], inplace=True)
            out_file = pl.Path(output.tsv_dir).joinpath(f"{sample_name}.chrY-regions-kmer-annot.bed")
            out_file.parent.mkdir(parents=True, exist_ok=True)
            new_tsv.to_csv(out_file, sep="\t", index=False, header=True)
    # END OF RUN BLOCK


localrules: unzip_color_unique_kmer_counts
rule unzip_color_unique_kmer_counts:
    input:
        zip = PROJECT_REPO_ROOT.joinpath(
            "annotation", "raw", "20250707_Peter_Bed_Files_ColorBlocks.ML.zip",
        ).resolve(strict=True)
    output:
        bed_dir = directory(WD.joinpath("region_kmer_annot", "color_unique_kmers"))
    shell:
        "unzip -o -j -d {output.bed_dir} {input.zip} "


localrules: normalize_color_unique_kmer_counts
rule normalize_color_unique_kmer_counts:
    input:
        bed_dir = rules.unzip_color_unique_kmer_counts.output.bed_dir
    output:
        tsv_dir = directory(WD.joinpath("region_kmer_annot", "norm_color_unique_kmers"))
    run:
        import hashlib as hl
        import numpy as np
        import pandas as pd
        import pathlib as pl
        import sys
        np.seterr(divide = 'raise')

        for bed_file in pl.Path(input.bed_dir).glob("*.bed"):
            # the format is of course idiosyncratic
            file_name = bed_file.name
            sample = file_name.split("_")[0]
            if sample not in SAMPLES:
                sys.stderr.write(f"\nWarning: skipping file - likely not a sample file: {file_name}\n")
                continue  # skip files that do not match any sample name
            df = pd.read_csv(
                bed_file,
                sep="\t",
                header=0,
            )
            df["region_id"] = df.apply(
                lambda row: hl.md5(
                    f"{row['#Contig']}{row['Start']}{row['End']}".encode("utf-8")
                ).hexdigest(),
                axis=1
            )
            df["kmerColor"] = df["kmerColor"].apply(normalize_label_name)

            # following: rank the possible labels by
            # their unique k-mer count and compute some
            # proxy for the confidence in the assignment
            # (enrichment = km(best label) / km(second-best label)
            ext_df = []
            for region, labels in df.groupby("region_id"):
                if labels.shape[0] == 1:
                    # only one label to choose from,
                    # take it as best hit, set enrichment
                    # to factor 100
                    ext_df.append(
                        (labels.index[0], labels["kmerColor"].iloc[0], 100)
                    )
                    continue
                # note 'ascending=false': rank 1 is the best hit, rank 2 second and so on
                ranks = labels["totalUniqueKmerHits"].rank(method="dense", ascending=False)
                top_rank = ranks.argmin()
                last_rank = ranks.argmax()
                if top_rank == last_rank:
                    # Several potential labels, but all have the same
                    # unique k-mer count and thus, no best match can be
                    # assigned here. Note that ML solves these cases by
                    # looking at all shared k-mers and then assigns the
                    # label that maximizes the number of shared k-mers.
                    # But we don't have that information available here.
                    ext_df.extend(
                        [(idx, "uncertain", 0) for idx in labels.index]
                    )
                else:
                    # at least two different ranks implies there is a best match
                    top_kmer = labels.loc[ranks.idxmin(), "totalUniqueKmerHits"]
                    assigned_label = labels.loc[ranks.idxmin(), "kmerColor"]
                    # note here: several labels could have been ranked as two,
                    # but all of them must have the same unique k-mer count,
                    # hence arbitrarily taking the first does not affect the
                    # computation
                    second_rank = ranks.index[ranks == 2][0]
                    second_kmer = labels.loc[second_rank, "totalUniqueKmerHits"]
                    try:
                        top_enrich = min(100, round(top_kmer / second_kmer, 2))
                    except FloatingPointError:
                        top_enrich = 100
                    ext_df.extend(
                        [(idx, assigned_label, top_enrich) for idx in labels.index]
                    )
            ext_df = pd.DataFrame.from_records(ext_df, columns=["index", "assigned_label", "top_enrich"])
            ext_df.set_index("index", inplace=True)

            df = df.join(ext_df)
            df.drop("region_id", axis=1, inplace=True)
            df.sort_values(["#Contig", "Start", "totalUniqueKmerHits"], inplace=True, ascending=[True, True, False])

            out_filename = f"{sample}_chrY-regions_uniq-kmer-counts.tsv"
            out_filepath = pl.Path(output.tsv_dir).joinpath(out_filename)
            out_filepath.parent.mkdir(parents=True, exist_ok=True)
            df.to_csv(out_filepath, sep="\t", index=False, header=True)
    # END OF RUN BLOCK


rule merge_aln_and_kmer_annotation:
    input:
        aln_bed = rules.check_realign_precision.output.bed,
        strand_kmer_tsv = rules.normalize_kmer_based_color_annotation.output.tsv_dir,
        uniq_color_kmer_tsv = rules.normalize_color_unique_kmer_counts.output.tsv_dir
    output:
        bed = WD.joinpath(
            "region_labels_aln_kmers",
            "{sample}.{ref}.chrY-regions.aln-kmer-merged.bed"
        )
    conda:
        GLOBAL_CONDA_ENVS.joinpath("seqtools.yaml")
    params:
        script=PROJECT_REPO_ROOT.joinpath(
            "codebase", "postproc-region-labels", "workflow",
            "scripts", "merge_kmer_annotation.py"
        ).resolve(strict=True),
        kmer_strand_info = lambda wildcards, input: pathlib.Path(
            input.strand_kmer_tsv,
            f"{wildcards.sample}.chrY-regions-kmer-annot.bed"
        ),
        kmer_color_info = lambda wildcards, input: pathlib.Path(
            input.uniq_color_kmer_tsv,
            f"{wildcards.sample}_chrY-regions_uniq-kmer-counts.tsv"
        ),
    shell:
        "{params.script} --aln-region-labels {input.aln_bed} "
        "--kmer-strands {params.kmer_strand_info} "
        "--kmer-region-labels {params.kmer_color_info} "
        "--output {output.bed}"


localrules: normalize_filtered_hmmer_hits
rule normalize_filtered_hmmer_hits:
    """This rule is highly application-specific because
    it depends on externally filtered high-quality HMMER
    hit (provided by Mark Loftus). These data come in slightly
    non-uniform format and must be normalized first.
    """
    input:
        hmmer_filtered = [
            pathlib.Path(PROJECT_CONFIG["remote_hilbert_prefix"]).joinpath(PROJECT_CONFIG["hmmer_filtered_dyz19"]),
            pathlib.Path(PROJECT_CONFIG["remote_hilbert_prefix"]).joinpath(PROJECT_CONFIG["hmmer_filtered_tspy"]),
            pathlib.Path(PROJECT_CONFIG["remote_hilbert_prefix"]).joinpath(PROJECT_CONFIG["hmmer_filtered_yq12"])
        ]
    output:
        hmmer_motifs = expand(
            WD.joinpath(
                "hmmer_filtered_hits", "{motif}",
                "{sample}.{motif}.chrY-hmmer-filtered-hits.bed"
            ),
            sample=SAMPLES,
            motif=["tspy", "dyz19", "yq12"]
        )
    run:

        for folder in input.hmmer_filtered:
            folder = pathlib.Path(folder).resolve(strict=True)
            motif_name = folder.name.replace("hmmerFilter", "")
            assert motif_name in ["tspy", "dyz19", "yq12"]
            for csv_file in folder.glob("**/*.csv"):
                if "old" in str(csv_file.parent):
                    continue
                sample = csv_file.name.split(".")[0]
                bed_df = load_ml_motif_hits(csv_file, motif_name)
                out_file = WD.joinpath(
                    "hmmer_filtered_hits", f"{motif_name}",
                    f"{sample}.{motif_name}.chrY-hmmer-filtered-hits.bed"
                )
                bed_df.to_csv(out_file, sep="\t", header=True, index=False)
    # END OF RUN BLOCK


localrules: merge_hmmer_hits_into_aln_kmer_regions
rule merge_hmmer_hits_into_aln_kmer_regions:
    input:
        regions = rules.merge_aln_and_kmer_annotation.output.bed,
        hmmer_hits = expand(
            WD.joinpath(
                "hmmer_filtered_hits", "{motif}",
                "{sample}.{motif}.chrY-hmmer-filtered-hits.bed"
            ),
            motif=["tspy", "dyz19", "yq12"],
            allow_missing=True
        )
    output:
        bed = WD.joinpath(
            "aln_kmer_hmmer", "merged_wo_qc",
            "{sample}.{ref}.chrY-regions.aln-kmer-hmmer.bed"
        )
    run:
        import pandas as pd
        import re

        hmmer = []
        for bed_file in input.hmmer_hits:
            motif = pd.read_csv(bed_file, sep="\t", header=0)
            hmmer.append(motif)
        hmmer = pd.concat(hmmer, axis=0, ignore_index=False)

        regions = pd.read_csv(input.regions, sep="\t", header=0)

        tag_motifs = build_redundant_motif_filter(set(
            ["tspy", "dyz19", "yq12"] + hmmer["name"].tolist()
        ))

        regions["is_replaced"] = regions["name"].apply(tag_motifs) | regions["second_best_guess"].apply(tag_motifs)
        regions = regions.loc[~regions["is_replaced"], :].copy()

        regions.drop("is_replaced", axis=1, inplace=True)

        hmmer["thickStart"] = hmmer["start"]
        hmmer["thickEnd"] = hmmer["end"]
        hmmer["assign_method"] = "hmmer"
        hmmer["second_best_guess"] = hmmer["name"]
        hmmer["kmer_top_enrich"] = 0
        hmmer["other_support"] = "unknown"
        hmmer["other_orientation"] = "."
        hmmer["cluster_id"] = -1

        regions = pd.concat([regions, hmmer], axis=0, ignore_index=False)
        regions.sort_values(["#seq", "start", "end"], inplace=True)

        assert not pd.isnull(regions).any(axis=0).any()

        regions.to_csv(output.bed, sep="\t", header=True, index=False)
    # END OF RUN BLOCK


rule run_all_postproc_labels:
    """potential TODO: add the reference kmer annotation
    analogous to the sample-level kmer annotation to
    have a proper baseline for accuracy
    (needs to be done by ML)
    """
    input:
        tsv = expand(
            rules.merge_hmmer_hits_into_aln_kmer_regions.output.bed,
            sample=[sample for sample in SAMPLES if sample not in ["RFGRC38-R1", "RFCHM13-J1"]],
            ref=list(MODULE_REF_GENOMES.keys())
        ),
        kmer_tsv = rules.normalize_kmer_based_color_annotation.output.tsv_dir,
        uniq_kmer_tsv = rules.normalize_color_unique_kmer_counts.output.tsv_dir,
        hmmer_motif_hits = rules.normalize_filtered_hmmer_hits.output.hmmer_motifs
